name: 'test-aks'

on: workflow_dispatch


jobs:

# dev
  test-aks: # job
    name: 'test-aks' # name for job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Azure logout
    - name: Azure aks 
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az aks get-versions --location eastus --output table

